name: docker-build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron:  '35 2 * * 2'

permissions: 
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Docker requires image tags to be in all lowercase
      -
        id: username-format
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}
      -
        name: Build and push (Alpine)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: alpine.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.username-format.outputs.lowercase }}/cron:latest
      -
        name: Build and push (Ubuntu)
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ubuntu.dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ steps.username-format.outputs.lowercase }}/cron:ubuntu
